-- phpMyAdmin SQL Dump
-- version 5.2.1deb3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 30, 2026 at 01:01 PM
-- Server version: 8.0.45-0ubuntu0.24.04.1
-- PHP Version: 8.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dbdictionary`
--

-- --------------------------------------------------------

--
-- Table structure for table `failed_attempts`
--

CREATE TABLE `failed_attempts` (
  `id` int NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `attempt_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `failed_attempts`
--

INSERT INTO `failed_attempts` (`id`, `ip_address`, `attempt_time`) VALUES
(1, '127.0.0.1', '2026-05-20 05:14:59'),
(2, '127.0.0.1', '2026-05-20 05:15:13'),
(3, '127.0.0.1', '2026-05-20 05:15:21'),
(4, '127.0.0.1', '2026-05-20 05:15:29'),
(5, '127.0.0.1', '2026-05-20 05:15:37'),
(6, '127.0.0.1', '2026-05-20 11:54:39'),
(7, '127.0.0.1', '2026-05-28 11:16:17');

-- --------------------------------------------------------

--
-- Table structure for table `sections`
--

CREATE TABLE `sections` (
  `s_id` int NOT NULL,
  `user_id` int NOT NULL,
  `username` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `deta` text COLLATE utf8mb4_general_ci,
  `last_activity` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `sections`
--

INSERT INTO `sections` (`s_id`, `user_id`, `username`, `deta`, `last_activity`) VALUES
(11, 46, 'rrr', '3c90lbqjh0u1ln53gscihi87nn', '2026-04-04 03:59:13'),
(12, 46, 'rrr', '3c90lbqjh0u1ln53gscihi87nn', '2026-04-04 03:59:34');

-- --------------------------------------------------------

--
-- Table structure for table `terms`
--

CREATE TABLE `terms` (
  `id` int NOT NULL,
  `term` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `trans` text COLLATE utf8mb4_unicode_ci,
  `defe` longtext COLLATE utf8mb4_unicode_ci,
  `picture` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `terms`
--

INSERT INTO `terms` (`id`, `term`, `trans`, `defe`, `picture`, `user_id`, `status`) VALUES
(9, 'tot', 'tot', 'tot', 'up/yyy.jpg ', NULL, 'approved'),
(10, 'tet', 'tet', 'tet', 'pic/04.jpg', NULL, 'approved'),
(11, 'eee', 'eee', 'eee', 'pic/1628636246584.jpeg', NULL, 'approved'),
(12, 'GSE242805', 'Transcriptomic profiling of human monocytes', 'High-throughput sequencing study investigating gene expression in human monocytes.', 'pic/ncbi_logo.png', NULL, 'approved'),
(13, 'GSE150392', 'Single-cell analysis of COVID-19 immune response', 'Study of PBMC samples from patients with severe SARS-CoV-2 infection.', 'pic/ncbi_logo.png', NULL, 'approved'),
(14, 'GSE332757', 'Resident mesenchymal progenitor cells require autocrine IGF-I in homeostatic and regenerating skeletal muscle', 'Fibro-Adipogenic Progenitors (FAPs) are muscle-resident mesenchymal stromal cells essential for homeostasis and regeneration but can produce fibrosis or intramuscular fat in pathological conditions. Insulin-like Growth Factor-I (IGF-I) regulates regeneration through actions on muscle fibers, satellite cells, macrophages, and extracellular matrix (ECM) remodeling, but has multiple sources. To assess the role of FAP-derived IGF-I, we generated inducible FAP-specific Igf1-deficient (FID) mice. Following BaCl₂ injury, FID muscles displayed impaired regeneration, with smaller fibers, fewer Pax7⁺ and MyoD⁺ cells, increased CD68⁺ macrophages, decreased collagen, and suppressed FAP proliferation. After glycerol-induced injury, FID muscles had reduced fat. Primary FID FAPs displayed blunted proliferation, upregulated immune-regulatory genes, and downregulated ECM and growth genes, with delayed fibrogenic and adipogenic differentiation. scRNA-seq of homeostatic muscle revealed reduced protein translation and ECM indices alongside increased senescence markers in FID samples. Taken together, FAP IGF-I is critical for FAP function, with direct and indirect impact on muscle regeneration.', 'pic/ncbi_logo.png', NULL, 'approved'),
(15, 'GSE319733', 'Tumor-draining lymph nodes in ovarian cancer lack germinal centers but harbor tumor-reactive memory B cells clonally linked to intra-tumoral B cells', 'The presence of B cells in tumors is correlated with a positive prognosis in several types of cancers, including high-grade serous ovarian cancer (HGSOC). These cells give rise to plasma cells (PCs) that originate from germinal centers (GCs) and secrete tumor-reactive antibodies. GCs also give rise to memory B cells (MBCs); yet, it is unknown if tumor-reactive MBCs form in cancer patients. Single-cell RNA-seq revealed that retroperitoneal lymph nodes (LNs) located near the tumor, host primarily class-switched resting MBCs. Immunoglobulin sequencing, clonal analysis, and generation of monoclonal antibodies demonstrated that these MBCs carried tumor-reactive antibodies, some of which bind MMP14, an enzyme abundantly expressed by HGSOC tumors. Although tumor-associated retroperitoneal LNs did not exhibit an active immune response, tumor binding of the MBCs derived from these LNs was dependent on somatic hypermutations (SHM), suggesting that they originated from a previous GC reaction. Different and overlapping types of MBC subpopulations were detected in the primary tumor and associated patient-matched LNs, some of which show clonal relationships between the two sites. Thus, our study extends our understanding of the anti-tumor memory response by revealing an inter-organ link between tumor-reactive MBC clones in ovarian cancer patients, which could potentially be manipulated in ovarian cancer patients.', 'pic/ncbi_logo.png', NULL, 'approved'),
(16, 'GSE297080', 'Influence of BM niches on leukemic B cells in PAX5-ELN mice', 'The bone marrow (BM) microenvironment plays a key role in supporting B cell development. In acute lymphoblastic leukemia (B-ALL), the acquisition of oncogenic driver mutations blocks B cell differentiation at specific stages. When these pre-leukemic cells acquire secondary mutations, B-ALL develops. However, the role of the BM microenvironment in pre-leukemic cell fate remains unknown. Here, using a murine model of spontaneous B-ALL development, we show that disrupted pre-BCR signaling in pre-leukemic cells modifies their fate. Blocking expression of the pre-BCR ligand Galectin-1 by the microenvironment impaired pre-leukemic cell proliferation and leukemia-initiating capacity. Consequently, B-ALL development was delayed, and B-ALL had a more mature phenotype, with cells expressing a BCR. Secondary mutations were also altered by changes to Galectin-1 expression. In its absence mutations almost exclusively affected IL-7R signaling rather than both pre-BCR and IL-7R signaling. These results show that signals from BM niches can directly influence pre-leukemic B cell fate.', 'pic/ncbi_logo.png', NULL, 'approved'),
(17, 'GSE297076', 'Influence of BM niches on pre-leukemic B cells in PAX5-ELN mice', 'The bone marrow (BM) microenvironment plays a key role in supporting B cell development. In acute lymphoblastic leukemia (B-ALL), the acquisition of oncogenic driver mutations blocks B cell differentiation at specific stages. When these pre-leukemic cells acquire secondary mutations, B-ALL develops. However, the role of the BM microenvironment in pre-leukemic cell fate remains unknown. Here, using a murine model of spontaneous B-ALL development, we show that disrupted pre-BCR signaling in pre-leukemic cells modifies their fate. Blocking expression of the pre-BCR ligand Galectin-1 by the microenvironment impaired pre-leukemic cell proliferation and leukemia-initiating capacity. Consequently, B-ALL development was delayed, and B-ALL had a more mature phenotype, with cells expressing a BCR. Secondary mutations were also altered by changes to Galectin-1 expression. In its absence mutations almost exclusively affected IL-7R signaling rather than both pre-BCR and IL-7R signaling. These results show that signals from BM niches can directly influence pre-leukemic B cell fate.', 'pic/ncbi_logo.png', NULL, 'approved'),
(18, 'GSE293119', 'Integration of Alzheimer’s GWAS, 3D genomics, and single-cell CRISPRi non-coding screen implicates causal variants in a microglial enhancer regulating TSPAN14. [RNA-Seq]', 'While GWAS have been successful in providing variant-to-trait associations for human complex diseases, functional dissection of the discovered loci has lagged behind. Here, we describe a variant-to-gene (V2G) mapping effort for Alzheimer’s disease (AD) to implicate causal variants and effector genes from the most recent AD GWAS meta-analyses (101 loci). We leveraged our genomics datasets comprising high-resolution promoter Capture C, ATAC-seq, and RNA-seq from brain-relevant cell types to fine-map AD GWAS variants, identifying 89 candidate causal SNPs and 69 effector genes. We then designed a single-cell CRISPRi screen to perturb candidate regulatory regions (n=74) and assess the transcriptional response in the human microglial cell line, HMC3. Our screen across ~97,000 cells identified 19 regulatory regions and 19 effector genes. We then elected to functionally dissect our top hit, the TSPAN14 locus, and we show that an intronic region containing AD-associated SNPs rs7080009, rs1870138, and rs1870137 is a microglia-specific enhancer, with the AD risk haplotype increasing its activity. CRISPR precise genomic deletion of this region decreases TSPAN14 expression, alters specific cellular pathways including cell adhesion, and decreases secreted levels of pro-inflammatory cytokines IL-6 and IL-8, which are known biomarkers of aging and AD. Our work provides a systematic framework to map GWAS signals to their effector genes for AD and other brain-related disorders, and provides robust leads to follow up with in-depth functional investigations.', 'pic/ncbi_logo.png', NULL, 'approved'),
(19, 'GSE293118', 'Integration of Alzheimer’s GWAS, 3D genomics, and single-cell CRISPRi non-coding screen implicates causal variants in a microglial enhancer regulating TSPAN14. [scRNA-Seq]', 'While GWAS have been successful in providing variant-to-trait associations for human complex diseases, functional dissection of the discovered loci has lagged behind. Here, we describe a variant-to-gene (V2G) mapping effort for Alzheimer’s disease (AD) to implicate causal variants and effector genes from the most recent AD GWAS meta-analyses (101 loci). We leveraged our genomics datasets comprising high-resolution promoter Capture C, ATAC-seq, and RNA-seq from brain-relevant cell types to fine-map AD GWAS variants, identifying 89 candidate causal SNPs and 69 effector genes. We then designed a single-cell CRISPRi screen to perturb candidate regulatory regions (n=74) and assess the transcriptional response in the human microglial cell line, HMC3. Our screen across ~97,000 cells identified 19 regulatory regions and 19 effector genes. We then elected to functionally dissect our top hit, the TSPAN14 locus, and we show that an intronic region containing AD-associated SNPs rs7080009, rs1870138, and rs1870137 is a microglia-specific enhancer, with the AD risk haplotype increasing its activity. CRISPR precise genomic deletion of this region decreases TSPAN14 expression, alters specific cellular pathways including cell adhesion, and decreases secreted levels of pro-inflammatory cytokines IL-6 and IL-8, which are known biomarkers of aging and AD. Our work provides a systematic framework to map GWAS signals to their effector genes for AD and other brain-related disorders, and provides robust leads to follow up with in-depth functional investigations.', 'pic/ncbi_logo.png', NULL, 'approved'),
(20, 'GSE291091', 'MSC-dependent intercellular communication: an interactome for skeletal muscle homeostasis and regeneration', 'Mesenchymal stromal cells (MSCs) support tissue homeostasis and regeneration, yet their molecular signals remain largely enigmatic. In skeletal muscle (SkM), MSCs, known as fibroadipogenic progenitors (FAPs), are essential for maintenance and repair, orchestrating these processes through intricate cellular communication networks. Given the critical role of SkM in lifelong health and longevity, FAP signaling has drawn significant interest as a potential therapeutic target and a model for MSC interactions. However, deciphering FAP-derived regulatory signals remains challenging due to their pleiotropic complexity. Here, we employ a systems-level approach to construct a comprehensive FAP interactome in both homeostatic and regenerating SkM. By integrating unique single-cell RNA sequencing atlases with advanced computational analyses, we identify putative FAP-mediated signaling pathways and validate their biological relevance through FAP depletion experiments, assessing disruptions in key pathways. This approach reveals novel signaling networks across diverse SkM cell populations, corroborates key FAP interactions from recent studies, and provides a valuable dataset for modeling MSC interactions and their roles in SkM homeostasis and regeneration.', 'pic/ncbi_logo.png', NULL, 'approved'),
(21, 'GSE331351', 'Single-Cell Multi-Omics Reveals Activation of the STAT3–PIM1 Axis in T Cell Subsets in Proteinase 3-ANCA-Positive Granulomatosis with Polyangiitis', 'Granulomatosis with polyangiitis (GPA) is an autoimmune disease marked by relapses and treatment-related morbidity. CD4⁺ T cells play a central role in GPA pathogenesis, but their molecular profile remains incompletely defined. This study aimed to characterize CD4⁺ T cells in proteinase 3-ANCA-positive GPA (PR3-GPA) patients using single-cell multi-omics to identify molecular signatures associated with disease activity. Peripheral blood mononuclear cells were obtained from PR3-GPA patients during active disease, remission, and healthy controls. Single-cell RNA sequencing and CITE-seq were used to define transcriptional and protein expression profiles of CD4⁺ T cell subsets. Findings were validated using RT-qPCR, flow cytometry–based assays, including phospho-flow cytometry, and in vitro inhibition assay. scRNA-seq and CITE-seq revealed upregulated PIM1 expression in CD4⁺ T cell subsets in active GPA compared to controls. Pim kinase inhibition reduced CD4⁺ T cell activation, proliferation, and cytokine production. These findings indicate that circulating CD4⁺ T cells in active PR3-GPA are characterized by activation of the STAT3–PIM1 axis, potentially driven by upstream IL-6 signaling.', 'pic/ncbi_logo.png', NULL, 'approved'),
(22, 'GSE324329', 'A kidney-protective mechanism via cellular oxidative stress reduction induced by CD5L protein', 'This SuperSeries is composed of the SubSeries listed below.', 'pic/ncbi_logo.png', NULL, 'approved'),
(23, 'GSE319771', 'Integrative Molecular Analyses of Inflammatory and Autoimmune Signals in Cardiac Sarcoidosis [Xenium]', 'Background: Cardiac sarcoidosis (CS) is an enigmatic disorder characterized by unexplained patchy, sterile granulomas intermixed with preserved myocardium, and fibrotic regions without granuloma, that causes arrhythmias, sudden cardiac death, and heart failure. The mechanisms producing this remarkable histopathology and disease progression remains unexplained.     Methods:  Using comprehensive single cell and spatial transcriptomic analyses, we characterized the cellular composition and gene expression in preserved, granulomatous, and fibrotic regions of human CS hearts. From the identification of clonally expanded cardiac B cells with rearranged immunoglobulin sequences, we reconstructed antibodies and screened libraries containing the human peptidome or microbial and allergen peptides to define reactive epitopes in CS heart.     Results: Ventricular regions with preserved, granulomatous, or fibrotic histopathology exhibited marked differences in cell composition and gene expression. Cardiomyocytes upregulated arrhythmogenic and inflammasome transcripts that would drive pyroptosis, and along with fibroblasts, activated chemoattractant cytokines that sustained myeloid and lymphoid infiltration. Within granulomas, abundant macrophages expressed modulators of cell-cell fusion and with Th17-skewed T cells upregulated B cell activating factor. Fibrotic regions, without active granulomas, exhibited tertiary lymphoid structures, with clonal expansion of mature B and plasma cells. Reconstructed antibodies derived from expanded B cell clones were inert to microbial and allergen peptides, but strongly reacted to periplakin, a desmosome protein, defining a target autoantigen.     Conclusions: CS is an inflammatory, autoimmune disorder that activates proarrhythmic and chemoattractant genes in cardiomyocytes within preserved myocardium, cell-cell fusion modulators in macrophages within granulomatous regions, and tertiary lymphoid structures in fibrotic regions that produce autoimmune antibodies. The identification of a target desmosome epitope, periplakin, links CS to arrhythmic desmosome cardiomyopathies, disorders with shared clinical manifestations. The centrality of humoral autoimmunity in perpetuating CS provides specific therapeutic opportunities to limit granuloma formation and B-cell activation. Parallel analytic strategies have potential to define autoantigens in other enigmatic cardiac immune disorders.', 'pic/ncbi_logo.png', NULL, 'approved'),
(24, 'GSE331455', 'scRNA-seq of limb-mesenhymal organoid derived from mouse embryo during digit-like morphogenesis', 'We performed single-cell RNA sequencing of mouse embryonic limb mesenchymal cells and limb mesenchymal organoids during digit-like morphogenesis. Distal and proximal limb mesenchymal cells were isolated from E11.5 Slc:ICR mouse embryos, labeled using lipid-DNA CellPlex/Feature Barcode oligonucleotides, and profiled either immediately as Day0 samples or after culture as limb mesenchymal organoids under serum-only control or Fgf8b/Wnt3a-supplemented conditions. The dataset includes Day0 distal and proximal cells, Day1 and Day2 control organoids, and Day1 and Day2 Fgf8b/Wnt3a-treated organoids. These data were used to characterize distal and proximal cell states, treatment-dependent transcriptional changes, and lineage/state trajectories associated with self-organized digit-like morphogenesis.', 'pic/ncbi_logo.png', NULL, 'approved'),
(25, 'GSE319770', 'Integrative Molecular Analyses of Inflammatory and Autoimmune Signals in Cardiac Sarcoidosis [snRNA-Seq]', 'BACKGROUND:Cardiac sarcoidosis (CS) is an enigmatic disorder characterized by unexplained patchy, sterile granulomas intermixed with preserved myocardium and fibrotic regions without granuloma. CS causes arrhythmias, sudden cardiac death, and heart failure. The mechanisms producing this remarkable histopathology and disease progression remain unexplained. METHODS:Using comprehensive single-cell and spatial transcriptomic analyses, we characterized the cellular composition and gene expression in preserved, granulomatous, and fibrotic regions of human CS hearts. From unexpectedly identified clonally expanded cardiac B cells with rearranged immunoglobulin sequences, we reconstructed antibodies and screened libraries comprising the human peptidome or microbial and allergen peptides to define reactive epitopes in CS hearts. RESULTS:Cellular composition and gene expression differed substantially in CS tissues with preserved, granulomatous, or fibrotic histopathology. Cardiomyocytes upregulated arrhythmogenic and inflammasome transcripts associated with pyroptosis. Cardiomyocytes and fibroblasts activated chemoattractant cytokines that sustained myeloid and lymphoid infiltration. Granulomas contained abundant macrophages expressing modulators of cell–cell fusion, along with Th17-skewed T cells that upregulated B-cell–activating factor, thereby promoting antibody production. Fibrotic regions, without active granulomas, exhibited tertiary lymphoid structures, with clonal expansion of mature B and plasma cells. Reconstructed antibodies derived from expanded B-cell clones were inert to microbial and allergen peptides, but reacted to PPL (periplakin), a desmosome protein, and other peptides expressed on cardiac cells. CONCLUSIONS:Progressive inflammatory signals in CS are mediated by chemoattractant genes in cardiomyocytes and fibroblasts within preserved myocardium, cell–cell fusion modulators in activated macrophages within granulomatous regions, and tertiary lymphoid structures in fibrotic regions that produce patient-specific autoimmune antibodies. Identification of PPL as a CS autoantigen may account for shared clinical manifestations in CS and arrhythmic desmosomal cardiomyopathies. CS autoantigens may underlie enigmatic histopathologic findings, perpetuate disease, and contribute to adverse outcomes. Uncovering an intracardiac humoral autoimmune axis in CS provides specific therapeutic opportunities to limit granuloma formation and B-cell activation, which may reduce arrhythmogenicity and progressive dysfunction. Parallel analytic strategies have potential to define autoantigens in other enigmatic cardiac immune disorders.', 'pic/ncbi_logo.png', NULL, 'approved'),
(26, 'GSE309936', 'mRNA expression profile of OVA-specific Th2 cells from cLNs of mice injected with or without OVA-specific IgE after nasal OVA challenge', 'To elucidate the role of systemic antigen-specific IgE in the local activation of Th2 cells during allergic rhinitis (AR), we employed an adoptive transfer-based AR mouse model. Mice were adoptively sensitized with OVA-specific IgE (OVA-IgE) and/or in vitro-differentiated OVA-specific Th2 (OVA-Th2) cells, followed by intranasal OVA challenge. Single-cell RNA sequencing was performed to analyze the mRNA expression profiles of Th2 cells isolated from cervical lymph nodes of mice injected with or without OVA-specific IgE. Freshly cultured OVA-Th2 cells were included as controls.', 'pic/ncbi_logo.png', NULL, 'approved'),
(27, 'GSE331294', 'Single-nucleus RNA-seq analysis of whole brains from 5xFAD mice with microglia-specific CD31 knockdown', 'We performed single-nucleus RNA sequencing (snRNA-seq) on whole-brain tissues from 5xFAD mice with microglia-specific CD31 knockdown to investigate transcriptional alterations associated with Alzheimer’s disease pathology. snRNA-seq analysis identified cell-type-specific transcriptional changes across multiple brain cell populations, including microglia, revealing that CD31 knockdown attenuated disease-associated microglial signatures and inflammatory responses while promoting pathways related to Aβ clearance. These findings provide insights into the role of microglial CD31 in regulating neuroinflammation and Alzheimer’s disease progression.', 'pic/ncbi_logo.png', NULL, 'approved'),
(28, 'GSE325196', 'Single Nuclei and Spatial Transcriptomic Datasets in Brain Metastases', 'We performed single nuclei and spatial transcriptomic sequencing on a cohort of solid tumor human brain metastasis specimens resected at Duke University Medical Center from 1998 to 2022. This includes 23 single nuclei specimens, 12 Visium standard specimens, and 4 Xenium specimens. These samples encompass metastases from lung cancer, breast cancer, melanoma, and sarcoma primaries. Analysis of these data revealed novel tumor-microenvironment cell-cell interactions associated with patient survival.', 'pic/ncbi_logo.png', NULL, 'approved'),
(29, 'GSE233462', 'Ubiquitin D drives colorectal cancer immune evasion and resistance to anti PD1 immunotherapy', 'Ubiquitin D drives colorectal cancer immune evasion and resistance to anti PD1 immunotherapy by suppressing FBXW7 mediaUbiquitin D drives colorectal cancer immune evasion and resistance to anti PD1 immunotherapy by suppressing FBXW7 mediated CD73 degradation [scRNA-seq] The majority of patients with colorectal cancer (CRC) can’t benefit from anti-PD-1 immunotherapy due to an insufficient T cell response in the tumor microenvironment (TME); however, the underlying mechanism remains unknown. Here, we show that ubiquitin D (UBD) in tumor cells inhibits CD8+ T cell‑mediated anti‑tumor responses, and consequently mediates resistance to anti‑PD‑1 immunotherapy in experimental and clinical CRC. Mechanistically, UBD disrupted E3 ligase F‑box and WD repeat domain‑containing 7 (FBXW7)‑induced proteasome degradation of CD73, thereby increasing the concentration of intracellular adenosine, which subsequently suppressed CD8+ T cell function in the TME. Importantly, blockade of CD73 sensitized UBD‑overexpressed cancer cells to anti-PD‑1 immunotherapy by restoring intratumor CD8+ T cell function. We have thus revealed a previously unrecognized mechanism for CRC resistance to anti‑PD‑1 therapy through UBD‑CD73‑adenosine mediated suppression of CD8+ T cells. This new information potentially provides a novel strategy to overcome resistance to PD‑1 blockade in patients with CRC.', 'pic/ncbi_logo.png', NULL, 'approved'),
(30, 'GSE332984', 'Single-cell RNA sequencing reveals acquisition of a FOXP3-positive regulatory-like state in relapsed TFH lymphoma', 'Nodal T follicular helper cell lymphomas (nTFHLs) are mature T-cell neoplasms characterized by transcriptional and phenotypic features of TFH cells. In this study, we analyzed relapsed TFH lymphoma samples using single-cell RNA sequencing, TCR repertoire analysis, whole-exome sequencing, and viral detection analysis. Single-cell transcriptomic profiling identified a dominant malignant T-cell population expressing canonical TFH-associated genes, with acquisition of a FOXP3-positive regulatory-like transcriptional state at relapse. T-cell receptor clonotype analysis demonstrated oligoclonal expansion within the malignant compartment. Targeted genomic profiling identified recurrent TET2 mutations together with PLCG1 and TP53 alterations. Viral detection analysis identified EBV sequences but no HTLV-1/2 sequences. Processed Seurat objects, cell-level metadata, mutation annotation tables, and viral detection results are provided.', 'pic/ncbi_logo.png', NULL, 'approved'),
(31, 'GSE332601', 'Spatial transcriptomics profiling of NDMA-induced liver injury in Mgmt-deficient mice across sex and time', 'Spatial transcriptomics (10x Genomics Visium) was performed on fresh-frozen liver tissue (left lobe) from Mgmt-/- mice treated with N-nitrosodimethylamine (NDMA) or saline vehicle during the juvenile period. The study includes male and female mice sacrificed at 10 weeks or 10 months post-birth to characterize spatially resolved transcriptomic changes associated with NDMA-induced liver damage and potential carcinogenesis over time. Mice carried the RaDR+/+; GPT+/+ genotype enabling detection of recombination and mutation events. Tissue sections were processed using the 10x Visium workflow, H&E stained, imaged, permeabilized for spatially barcoded cDNA synthesis, and sequenced on an Illumina NextSeq 500.', 'pic/ncbi_logo.png', NULL, 'approved'),
(32, 'GSE330160', 'Apelin analog treatment reverses severe pulmonary arterial hypertension and right ventricular heart failure', 'Pulmonary arterial hypertension (PAH) is a progressive disease marked by pulmonary vascular remodeling, elevated pulmonary pressures, and right ventricular (RV) failure. In this study, a sugen-hypoxia rat model of PAH was used to evaluate a novel, degradation-resistant apelin analog targeting the apelinergic pathway, which is implicated in pulmonary vascular remodeling. Treatment with the apelin analog reversed key pathological features of PAH, including pulmonary vascular lesions, elevated pulmonary arterial pressures, RV dilation and dysfunction, and early cardiorenal syndrome. The therapy also reduced RV cardiomyocyte and fibroblast activation caused by pressure overload. Single-nucleus RNA sequencing of the lungs and RV demonstrated that apelin analog treatment activated protective molecular programs, notably restoring balance between protective BMPR2 signaling and pathogenic TGFBR2 signaling. Overall, these findings suggest that exogenous apelin therapy may represent a promising strategy to reverse pulmonary vascular and cardiac remodeling in PAH and warrants further clinical investigation.', 'pic/ncbi_logo.png', NULL, 'approved'),
(33, 'GSE326950', 'Spatial transcriptomics identifies dysregulated programs across neural and non-neural tissues in spinal muscular atrophy', 'Spinal muscular atrophy (SMA) is caused by insufficient levels of the survival motor neuron (SMN) protein and clinically manifests as profound weakness due to motor neuron degeneration. While recent evidence suggests it is a multisystem disorder, the pathological programs in neural and peripheral tissues are poorly understood. We applied spatial transcriptomics to cross-sections from the entire lumbar region of pre-symptomatic SMA and control mice to define early, tissue-wide transcriptional consequences of SMN deficiency. This approach enabled spatially preserved analysis of spinal cord, dorsal root ganglia, muscle, bone, cartilage, bone marrow, adipose, and connective tissues within their native anatomical context. Within the SMA spinal cord, motor neuron associated regions and ventral interneurons exhibited upregulation of neurofilaments, tubulin isoforms, and microtubule transport machinery. Neurofilament changes were largely restricted to motor neurons, and tubulin dysregulation extended broadly across ventral regions. Multiple tissues displayed collagen and extracellular matrix gene dysregulation at post-natal day 4. Skeletal muscle demonstrated fiber type-specific stress responses, including induction of atrophy-associated genes, while bone displayed an osteoclast-dominant transcriptional signature, consistent with accelerated resorption and a pro-osteoporotic state. Bone marrow transcriptomes indicated activation of neutrophil degranulation, innate immune signaling, and osteoclastogenic pathways, identifying bone marrow as an active inflammatory and skeletal regulatory niche in SMA. Adipose tissue exhibited extracellular matrix dysregulation, complement activation, profibrotic TGF-β signaling, and stress-induced lipolysis. These findings reveal that SMN deficiency drives early transcriptional reprogramming across multiple tissues well before motor neuron loss and identify non-neuronal pathological programs that offer therapeutic targets for improving long-term outcomes in SMA.', 'pic/ncbi_logo.png', NULL, 'approved'),
(34, 'GSE319970', 'Nr2f1a and Isl1 repress acquisition of epicardial identity in venous atrial cardiomyocytes', 'Regulatory networks that maintain cardiomyocyte identity are not completely understood. Here, we examined the relationship of the transcription factors (TFs) Nr2f1a and Isl1, which respectively repress and promote pacemaker cardiomyocyte (PC) differentiation within the venous pole of zebrafish atria. Using zebrafish nr2f1a;isl1 mutants, we found that loss of Isl1 exacerbates the inability to maintain atrial cardiomyocyte (AC) identity found in nr2f1a mutant hearts. Subsequently, while nr2f1a;isl1 mutants have a failure of PC differentiation and inability of ACs to transdifferentiate into PC identity, ACs in nr2f1a;isl1 mutant hearts lose myocardial marker expression, gain epicardial cell (EC) gene expression, and exit the myocardial layer. Single cell RNA-seq analysis of hearts supports that the ACs and ECs of nr2f1a;isl1 mutant embryos share common myocardial and EC transcriptomic signatures. Depletion of tcf21 and tbx18 in nr2f1a;isl1 mutants was sufficient to prevent the acquisition of EC identity within putatively transdifferentiating ACs. Thus, our results reveal reiterative requirements for Nr2f and Isl1 TFs in binary fate decisions within the genetic hierarchy that maintains distinct AC, PC, and EC identities at the venous pole of vertebrate hearts.', 'pic/ncbi_logo.png', NULL, 'approved'),
(35, 'GSE310482', 'Cell autonomous regional differences in oligodendrocyte precursor cell development and response to oncohistone H3.3 K27M', 'This SuperSeries is composed of the SubSeries listed below.', 'pic/ncbi_logo.png', NULL, 'approved'),
(36, 'GSE290817', 'Cell autonomous regional differences in oligodendrocyte precursor cell development and response to oncohistone H3.3 K27M [scRNA-seq]', 'Diffuse midline glioma (DMG) is an incurable tumor arising in brainstem and midline structures. Most DMGs harbor missense histone H3 mutations replacing lysine 27 with methionine (H3 K27M). The mechanisms underlying regional selectivity for H3 K27M mutations, which are found almost exclusively in DMG, are not well understood. Here, we use a conditional knock-in mouse model to probe the postnatal brain region-specific oncogenic effects of H3.3 K27M in embryonic GFAP+ neural stem cells. We show that H3.3 K27M reduces oligodendrocyte differentiation in a region-specific manner and increases postnatal proliferation of distinct progenitor states by brain region in vivo, selectively expanding the oligodendrocyte-lineage in the ventral pons. Cellular morphology, marker expression, and transcriptomic analyses of primary region-specific mouse OPC cultures demonstrated cell-intrinsic differences in wild-type brainstem and forebrain OPC differentiation dynamics. H3.3 K27M drives cell-autonomous increase in brainstem-derived OPC proliferation and disrupts intrinsic region-specific transcriptional programs, delaying differentiation in forebrain-derived OPCs and restraining full maturation of brainstem-derived OPCs. H3.3 K27M-mediated changes include brainstem-selective upregulation of genes in Bmp, Wnt, and Notch pathways that are relevant in DMG pathogenesis. Our findings reveal that H3.3 K27M differentially disrupts cell-autonomous regional oligodendrocyte development, which may provide an opportunistic window for brainstem-selective gliomagenesis.', 'pic/ncbi_logo.png', NULL, 'approved'),
(37, 'GSE276297', 'Establishing Chicken Primordial Germ Cell Lines with Gonad Chimerism [scRNA-Seq]', 'We found that chicken PGCs derived from E7 to E11 gonads were heterogeneity which could cultre in vitro for a long time with germline chimerism and the ratio of chimerism was  improved through second blood vessel injection.', 'pic/ncbi_logo.png', NULL, 'approved'),
(38, 'GSE275542', 'Dissecting tissue-specific microenvironments in acute myeloid leukemia [scRNA-Seq]', 'Acute myeloid leukemia (AML) is a blood cancer with poor survival outcomes. Limited studies have reported lethal complications in patients due to leukemia infiltration into solid tissues such as the lung, but the related mechanisms remain understudied. Here, we map the transcriptional landscape of the mouse lung microenvironment at single-cell resolution in the AML-infiltrated lungs. Our analysis demonstrated a considerable remodeling of the lung microenvironment under leukemia conditions, as indicated by expansion of stromal myofibroblasts and reduction of endothelial capillary aerocytes. Those changes were accompanied by changes in immune resident cells of the lung microenvironment, as supported by reduction of B- and T- cell proportions, and increased frequencies of activated neutrophils and monocyte populations. We show an induction of inflammatory response within the microenvironment of the leukemic lung. We dissect the spatial interplay between AML and the lung microenvironment, and we identify previously unappreciated interactions driven by inflammatory mediators within the leukemic milieu. Of note, we show that Lgals9 (encoding for Galectin-9) mediates most of cell-cell interactions within the microenvironment of the AML-infiltrated lungs. LGALS9 is highly expressed in AML patients and its role in AML remains elusive. Targeting Galectin-9 reduces the AML burden in the lungs and reverses the infiltration phenotype. Combining single-cell, spatial transcriptomics approaches and functional experimentsin vivo, our study is the first to characterize the pulmonary infiltration phenotype in AML, opening the route for novel treatment strategies in acute leukemia.', 'pic/ncbi_logo.png', NULL, 'approved'),
(39, 'GSE269045', 'Inflammatory immune modulators of AML lung infiltration and respiratory failure', 'This SuperSeries is composed of the SubSeries listed below.', 'pic/ncbi_logo.png', NULL, 'approved'),
(40, 'GSE269042', 'Dissecting tissue-specific microenvironments in acute myeloid leukemia (scRNA-Seq Niche)', 'Acute myeloid leukemia (AML) is a blood cancer with poor survival outcomes. Limited studies have reported lethal complications in patients due to leukemia infiltration into solid tissues such as the lung, but the related mechanisms remain understudied. Here, we map the transcriptional landscape of the mouse lung microenvironment at single-cell resolution in the AML-infiltrated lungs. Our analysis demonstrated a considerable remodeling of the lung microenvironment under leukemia conditions, as indicated by expansion of stromal myofibroblasts and reduction of endothelial capillary aerocytes. Those changes were accompanied by changes in immune resident cells of the lung microenvironment, as supported by reduction of B- and T- cell proportions, and increased frequencies of activated neutrophils and monocyte populations. We show an induction of inflammatory response within the microenvironment of the leukemic lung. We dissect the spatial interplay between AML and the lung microenvironment, and we identify previously unappreciated interactions driven by inflammatory mediators within the leukemic milieu. Of note, we show that Lgals9 (encoding for Galectin-9) mediates most of cell-cell interactions within the microenvironment of the AML-infiltrated lungs. LGALS9 is highly expressed in AML patients and its role in AML remains elusive. Targeting Galectin-9 reduces the AML burden in the lungs and reverses the infiltration phenotype. Combining single-cell, spatial transcriptomics approaches and functional experimentsin vivo, our study is the first to characterize the pulmonary infiltration phenotype in AML, opening the route for novel treatment strategies in acute leukemia.', 'pic/ncbi_logo.png', NULL, 'approved'),
(41, 'GSE269041', 'Dissecting tissue-specific microenvironments in acute myeloid leukemia (scRNA-Seq Immune)', 'Acute myeloid leukemia (AML) is a blood cancer with poor survival outcomes. Limited studies have reported lethal complications in patients due to leukemia infiltration into solid tissues such as the lung, but the related mechanisms remain understudied. Here, we map the transcriptional landscape of the mouse lung microenvironment at single-cell resolution in the AML-infiltrated lungs. Our analysis demonstrated a considerable remodeling of the lung microenvironment under leukemia conditions, as indicated by expansion of stromal myofibroblasts and reduction of endothelial capillary aerocytes. Those changes were accompanied by changes in immune resident cells of the lung microenvironment, as supported by reduction of B- and T- cell proportions, and increased frequencies of activated neutrophils and monocyte populations. We show an induction of inflammatory response within the microenvironment of the leukemic lung. We dissect the spatial interplay between AML and the lung microenvironment, and we identify previously unappreciated interactions driven by inflammatory mediators within the leukemic milieu. Of note, we show that Lgals9 (encoding for Galectin-9) mediates most of cell-cell interactions within the microenvironment of the AML-infiltrated lungs. LGALS9 is highly expressed in AML patients and its role in AML remains elusive. Targeting Galectin-9 reduces the AML burden in the lungs and reverses the infiltration phenotype. Combining single-cell, spatial transcriptomics approaches and functional experimentsin vivo, our study is the first to characterize the pulmonary infiltration phenotype in AML, opening the route for novel treatment strategies in acute leukemia.', 'pic/ncbi_logo.png', NULL, 'approved'),
(42, 'GSE332846', 'Case of Complete Response to Immunotherapy in MMR-Deficient Prostate Cancer Associated with NK-like and CD4+CD8+ T-cells', 'Mismatch repair deficiency (dMMR) and microsatellite instability (MSI-H) are rare in prostate cancer, occurring in 2-4% of cases. These defects result in increased genomic instability and elevated tumor mutational burden (TMB), which can support responses to immune checkpoint inhibitors (ICIs). Here, we report a patient with locally-advanced Gleason 5+5=10 prostatic adenocarcinoma harboring MSH2 and MSH6 genomic deletions with ultrahigh TMB (>250 mutations/megabase) in whom pembrolizumab resulted in a striking complete radiographic, pathologic, and molecular response. Using digital-spatial microscopy, single-cell RNA/TCR-sequencing, and multiplex cytometry, we identify atypical tumor-infiltrating T-cells with natural killer-like phenotypes and CD4+CD8+ (double-positive) lymphocytes. These unique and clonal T-cell populations expand preferentially following ICI and adopt terminally-differentiated and cytotoxic profiles that may drive clinical response. Similar T-cells are also present in diverse cancers and expand exclusively in ICI-responsive patients. These findings inform on cellular mechanisms by which immunotherapies may mediate profound responses in patients with dMMR solid tumors.', 'pic/ncbi_logo.png', NULL, 'approved'),
(43, 'GSE332787', 'Meiotic pairing through barcode-like satellite DNA repeats', 'During meiosis, chromosomes must find, pair and synapse with their homologous partner in the crowded milieu of the nucleus, without being entangled by non-homologous chromosomes1. Generally, homology detection is thought to rely on recombination between the homologous chromosomes. However, pairing and synapsis can occur in the absence of recombination2–10, suggesting alternate mechanisms which discriminate between homologous and non-homologous associations. In many eukaryotes, tandem repeats known as satellite DNA are known to facilitate inter-chromosomal associations11. Notably, their non-uniform distribution across chromosomes gives rise to homologue-specific satellite DNA ‘barcodes’12–14, which have been speculated to enable meiotic pairing15–18. However, the inability to manipulate these repeats in most model organisms means that satellite DNA function in meiotic pairing remains actively debated. Here, we use satellite DNA deletion, duplication, and translocation strains that are unique to Drosophila to demonstrate that repeat mismatches perturb meiotic pairing, particularly at centromeres and pericentromeres. Strains containing satellite DNA mismatches exhibit pairing defects that are likely driven by the incorrect association of similar repeats on non-homologous chromosomes. Notably, defective pairing also occurs in the progeny of D. melanogaster natural populations that have diverged in their satellite DNA content. In the absence of homozygous satellite DNA arrays, we further show that pairing is antagonized by the HORMAD protein, Mad2, while a Pachytene checkpoint 2 (Pch2)-dependent meiotic delay can restore pairing. Finally, compromised meiotic pairing is strongly correlated with mid-oogenesis cell death, a quality control mechanism that likely culls defective oocytes to prevent chromosome mis-segregation and aneuploidy. Therefore, our findings resolve the debate on satellite DNA functionality by providing evidence for a role in meiotic pairing. We propose that this repeat-based pairing mechanism exerts an underappreciated selective pressure, constraining the divergence of these rapidly evolving tandem repeats within interbreeding natural populations.', 'pic/ncbi_logo.png', NULL, 'approved'),
(44, 'GSE332708', 'Hybrid In Vivo Breast Cancer Model Reveals Transcriptomic Insights into Cancer Progression with Age', 'Aging is a key risk factor for breast cancer; however, the independent effects of the aged extracellular matrix (ECM) remain understudied. To address this, we developed a novel hybrid in vivo model that enables the independent investigation of age-related ECM influences on breast cancer development and progression. To examine the effects of genes known to be enriched in a cancerous and aged microenvironment, we first seeded normal or stable knockdown cells onto decellularized ECM (dECM) from aged murine mammary glands and implanted them into young Rag1-/- mice. We identified LOX as a principal driver of tumor progression, with knockdown reducing invasion, in vitro and in vivo, and stress-related pathways. To further isolate the independent influence of ECM aging on tumor growth, normal MCF10A cells were seeded atop young or aged matrices and implanted. Aged tumors exhibited significantly greater volume and a larger tumorigenic region when compared to young tumors, with single-cell RNA sequencing revealing enrichment of inflammatory and invasive genes. Together, these findings identify LOX as a driver of tumor progression and a potential therapeutic target and demonstrate that the aged ECM alone is sufficient to promote breast cancer progression.', 'pic/ncbi_logo.png', NULL, 'approved'),
(45, 'GSE331226', 'Metabolic–Epigenetic Rewiring of CCR5 hi Monocytes Sustains Long-Term Trained Immunity Against Lethal Sepsis [scRNA-seq]', 'Trained immunity enhances innate host defense by endowing monocytes with memory-like properties, yet the underlying integrated metabolic and epigenetic mechanisms remain elusive. Here, we demonstrate that co-immunization with Bacillus Calmette–Guérin (BCG) and bacterial lipoprotein (BLP) induces a durable form of trained immunity that provides robust, long-term protection against polymicrobial sepsis from early life into adulthood. Single-cell RNA sequencing revealed that this effect is mediated by an expansion of CCR5hi memory-like monocytes with enhanced antimicrobial capacity. Mechanistically, BCG+BLP vaccination activated the AKT–mTOR–HIF-1α axis, driving glycolytic reprogramming and subsequent lactate accumulation. We found that elevated lactate then promoted KAT2B-dependent histone H3K18 lactylation, an epigenetic mark directly facilitating the transcription of phagocytic and inflammatory genes. Critically, CCR5hi monocytes isolated from vaccinated human cord blood recapitulated these lactate-driven lactylation and trained immunity features. Together, our findings define a novel lactate–KAT2B–H3K18la epigenetic axis that orchestrates the long-term reprogramming of CCR5hi monocytes, highlighting CCR5hi monocytes as a promising therapeutic target for modulating innate immunity against lethal sepsis', 'pic/ncbi_logo.png', NULL, 'approved'),
(46, 'GSE313451', 'LeishDog: a single-cell transcriptome atlas of peripheral blood immune cells spanning progressive canine leishmaniosis', 'Controlling visceral leishmaniasis (VL) requires not only addressing human disease but also targeting animal reservoirs, particularly domestic dogs, which are critical hosts that sustain zoonotic Leishmania infantum transmission. Although considerable advances have been made, the immune mechanisms underlying the transition from asymptomatic infection to symptomatic disease remain ill-defined, both in humans and dogs. To address this unresolved question, we generated a comprehensive atlas of peripheral immune cells from naturally-infected dogs and uninfected controls. The LeishDog Atlas captures the cellular and transcriptional complexity underlying canine visceral leishmaniosis (CanL), tracing shifts in immune composition and gene expression across progressive, well-defined disease stages. Notably, we identified distinct myeloid, CD4+ and CD8+ T cell phenotypes associated with severe disease. This resource provides a valuable framework for understanding systemic immune dysregulation in CanL, and establishes a foundation for comparative, translational, and mechanistic studies of CanL immunopathology.', 'pic/ncbi_logo.png', NULL, 'approved'),
(47, 'GSE301221', 'APOE-mediated immunometabolic reprogramming of macrophages drives lipid delivery to tumor cells in clear-cell renal cell carcinoma — a metabolic checkpoint', 'Clear cell renal cell carcinoma (ccRCC) is the most common and lethal subtype of kidney cancer. Extensive evidence highlights the critical role of the von Hippel-Lindau (VHL) tumor suppressor gene in the initiation and progression of ccRCC. Our previous studies demonstrated that VHL deficiency in renal tubular epithelial cells promotes activation of the endothelial vascular network and facilitates immune cell infiltration, particularly by macrophages (Ms), into the ccRCC microenvironment. These interactions between VHL-deficient renal cells and the recruited stromal components are essential for ccRCC development. In our investigation of ccRCC-associated macrophages, we observed a significant upregulation of genes related to lipid metabolism in MΦs co-cultured with VHL-deficient tubular cells. Further analysis confirmed that these tumor-associated macrophages (TAMs) actively uptake lipids, and we called them lipid-laden macrophages (LLMs). Notably, Apolipoprotein E (APOE) emerged as one of the most highly upregulated lipid-related genes. Given APOE’s established function as a lipid-binding protein involved in lipoprotein formation and lipid uptake, we hypothesize that these macrophages transfer lipid contents to VHL-deficient tubular cells, thereby promoting the lipid-rich “clear cell” phenotype characteristic of ccRCC. To further investigate this mechanism, we isolated macrophage populations with high (APOEhi. MΦs) and low (APOElo. MΦs) APOE expression, along with control macrophages (MΦCtr), from the co-culture system. We then performed mRNA sequencing to elucidate the transcriptional landscape and functional roles of LLMs in ccRCC pathogenesis.', 'pic/ncbi_logo.png', NULL, 'approved'),
(48, 'GSE298522', 'A temporal single-nucleus atlas of the hippocampus in temporal lobe epilepsy mice unveils neuroprotective IGF1+ microglia', 'Epilepsy is a complex chronic disease characterized by intricate interactions between neurons and various types of glial cells during its pathogenesis. Understanding the molecular sequence of events underlying epilepsy onset and progression is critical for identifying molecular and cellular targets for therapeutic development. In this study, we aimed to reveal the dynamic cell-type-specific responses in TLE hippocampal tissue following KA induction, and identify cellular and molecular mechanisms that either promote or restrict epileptic seizures.', 'pic/ncbi_logo.png', NULL, 'approved'),
(49, 'GSE331465', 'Epicardial fat drives macrophage response in atrial cardiomyopathy [scRNA-Seq]', 'Single-cell RNA sequencing was performed on atrial cells isolated from mice fed either normal diet (ND) or high-fat diet (HFD) for 2 or 4 months to investigate immune and stromal remodeling during obesity-associated atrial cardiomyopathy. Distinct Lyve1+ resident and CCR2+ monocyte-derived macrophage populations were identified in obese mouse atria and were associated with atrial adiposity, fibro-fatty remodeling, and atrial fibrillation progression.', 'pic/ncbi_logo.png', NULL, 'approved'),
(50, 'GSE331446', 'Epicardial fat drives macrophage response in atrial cardiomyopathy', 'Inflammation contributes to atrial fibrillation (AF) and atrial cardiomyopathy (ACM). Spatial transcriptomic profiling of human right atrial appendage FFPE sections identified macrophage-associated fibro-fatty remodeling and inflammatory gene expression patterns associated with atrial adiposity during ACM progression.', 'pic/ncbi_logo.png', NULL, 'approved');
INSERT INTO `terms` (`id`, `term`, `trans`, `defe`, `picture`, `user_id`, `status`) VALUES
(51, 'GSE328074', 'Single-nucleus transcriptomic atlas of the mouse medial thalamus', 'The mediodorsal thalamus and adjacent midline nuclei are critical for higher-order cognition and neuropsychiatric disease, yet their cellular organization remains incompletely defined. The objective of this study was to characterize the cellular composition and transcriptional organization of the mouse medial thalamus. Single-nucleus RNA sequencing was used to identify neuronal cell types, assign transcriptional clusters to anatomical nuclei, and define gene expression patterns underlying thalamic organization. A further goal was to compare these features across species to identify conserved transcriptional patterns and differences in cell type composition, including neuronal populations expanded in humans relative to mice. This dataset provides a transcriptomic atlas of the medial thalamus and a resource for investigating cell type diversity, functional organization, and cross-species specialization.', 'pic/ncbi_logo.png', NULL, 'approved'),
(52, 'GSE319717', 'Implications for postpartum reprograming of SEMA7A and SOX9 in mammary cells and breast cancer', 'Postpartum mammary gland involution is a coordinated process of cell death and remodeling that returns the tissue to a near pre-pregnant state following lactation and weaning. In models of postpartum breast cancer, defined as breast cancer diagnosed in women under age 45 and within 10 years of recent childbirth, involution induces durable phenotypes in breast tumor cells that promote progression and are associated with increased risk for therapeutic resistance, metastasis, and death in patients. SRY-Box Transcription Factor 9 (SOX9), a known regulator of mammary stem and progenitor cells, also promotes resistance to therapy and metastasis in breast cancers. Yet the contribution of SOX9 to the involution process is not well understood. We utilized single-cell RNA sequencing of mouse mammary glands during involution to delineate Sox9-expressing cell populations during lactation and involution. We found that Sox9 mRNA is primarily expressed in luminal progenitor cells that are largely absent during lactation and present during early involution. We also reveal that Sox9 is involved in a shift in cell state from lactational to non-lactational and is expressed in the surviving cells during involution. Prior work revealed that Semaphorin-7a (SEMA7A) also promotes cancer stem cell and pro-survival phenotypes in luminal progenitor cells during involution, and we observe a population of luminal progenitor cells that co-expresses Sox9 and Sema7a during involution. Mechanistically, we demonstrate that knockdown of Sox9 in cultured mammary epithelial cells results in increased SEMA7A expression, mesenchymal phenotypes, and loss of lactogenic differentiation capacity, identifying a potential regulatory axis where SOX9 balances SEMA7A expression in normal mammary epithelium and that disruption of this balance results in a dedifferentiated state that resembles mesenchymal cells. We validated a spatial relationship between SOX9 and SEMA7A proteins in a unique set of breast tissue samples from healthy human donors to show co-expression during early involution. In breast cancer datasets, we observe elevated expression of SOX9 and SEMA7A in triple-negative breast cancers, as well as in the mesenchymal subtype of triple-negative breast cancers, suggesting disruption of this regulatory axis in breast cancer. Finally, we observe that co-expression increases metastatic risk in both estrogen receptor-negative and -positive breast cancers. Collectively, these findings define a novel SOX9–SEMA7A relationship in healthy mammary tissues and illustrate how studies of normal progenitor cell phenotypes can delineate cellular mechanisms that contribute to breast tumor progression. ', 'pic/ncbi_logo.png', NULL, 'approved'),
(53, 'GSE317219', 'An Integrated Single-Cell and Spatial Proteotranscriptomics Atlas of Fibroblast-Driven Immunoregulation within the Human Adult Oral Cavity', 'The immunoregulatory architecture of human oral tissues remains poorly defined despite their central role as barrier interfaces. We present the first integrated single-cell and dual-platform, spatial-proteotranscriptomic atlas of oral tissues, profiling >250,000 single-cell transcriptomes and >4 million spatially-resolved cells across 13 niches. Using our AI-enabled AstroSuite (TACIT, Constellation, STARComm, hist2omics), we defined tissue cellular neighborhoods (TCNs) and multicellular interaction modules (MCIMs) in health, revealing peri-epithelial fibroblast-centered hubs enriched for effector cytokines. We harmonized eight fibroblast subtypes (universal, immune, peri-epithelial, peri-vascular, peri-neural, APC-like, stress-responsive, and myofibroblasts) with stress-responsive subtypes partitioning between mucosae (Type I) and glands (Type II). Spatial multiomics mapped spatially recurrent receptor–ligand programs and identified mucosal stress-responsive fibroblasts as putative immunoregulatory hubs. In chronic periodontitis, niche-aware integration of healthy and diseased datasets revealed rewiring of fibroblast phenotypes and ligand::receptor networks into interdigitated inflammatory and reparative niches. Disease neighborhoods exhibited fragmentation, expansion of MHC-I⁺, MHC-II⁺, and PD-L1⁺ fibroblasts, and predicted spatial engagement with T cells at ectopic lymphoid structures. Drug2Cell analysis highlighted druggable stromal::immune networks. Together, this proteotranscriptomic atlas positions fibroblasts as central architects of structural immunity in human oral tissues and establishes a scalable framework for precision targeting of stromal::immune ecosystems across other barrier organs in health and chronic disease.', 'pic/ncbi_logo.png', NULL, 'approved'),
(54, 'GSE311381', 'Cellular composition of tissue-resident monocyte-lineage cells reveal heterogeneity during inflammatory arthritis, Figure 5 & 6', 'CITE-seq analysis of joint myeloid niche reveals the heterogeneity of tissue-resident monocyte-lineage cells during the progression of acute arthritis inflammation.', 'pic/ncbi_logo.png', NULL, 'approved'),
(55, 'GSE311380', 'Cellular composition of tissue-resident monocyte-lineage cells reveal heterogeneity during inflammatory arthritis, Figure 2 & 3', 'CITE-seq analysis of joint myeloid niche reveals the heterogeneity of tissue-resident monocyte-lineage cells at steady-state and 7 days post Clo-lip administration.', 'pic/ncbi_logo.png', NULL, 'approved'),
(56, 'GSE308772', 'Distinct development-associated roles of rice histone variant H2A.X in suppressing deposition of active H3K4me3 marks and in restricting H2A.W incorporation [smallRNA-Seq]', 'Histone variant H2A.X is a well-conserved protein that plays crucial roles in mediating DNA damage response across eukaryotes. Although H2A.X expresses even without any stress, and decorates gene bodies of actively expressed genes, it is not known if H2A.X has functions beyond DNA damage repair. Using genetic, high throughput genomics and molecular approaches, we identified a previously unappreciated role of H2A.X in regulating development-associated genes. H2A.X suppressed the deposition of active H3K4me3 marks over gene bodies and Transposable elements (TE)s, specifically regulating several root development, photosynthesis, and pigmentation-related genes as seen by the impairment of these processes in h2a.x ko plants. H2A.X also suppressed global deposition of H3K9me2 repressive mark by restricting activity of H2A variant H2A.W. In agreement with this, there was a genome-wide re-localization of H2A.W to TEs and a few genes in h2a.x ko plants. H2A.X overexpressing plants exhibited stress phenotypes including increased anthocyanin levels, mimicking the transcriptome of DNA damaged wildtype plants. The transcriptome of kd lines of FACT complex, a known chaperone of H2A.X, was largely similar to that of h2a.x ko, suggesting that the development-associated functions of FACT is at least partially due to H2A.X. These results suggest a key role of H2A.X in regulating competing histone marks and this function might be conserved across plants.', 'pic/ncbi_logo.png', NULL, 'approved'),
(57, 'GSE308771', 'Distinct development-associated roles of rice histone variant H2A.X in suppressing deposition of active H3K4me3 marks and in restricting H2A.W incorporation [RNA-Seq]', 'Histone variant H2A.X is a well-conserved protein that plays crucial roles in mediating DNA damage response across eukaryotes. Although H2A.X expresses even without any stress, and decorates gene bodies of actively expressed genes, it is not known if H2A.X has functions beyond DNA damage repair. Using genetic, high throughput genomics and molecular approaches, we identified a previously unappreciated role of H2A.X in regulating development-associated genes. H2A.X suppressed the deposition of active H3K4me3 marks over gene bodies and Transposable elements (TE)s, specifically regulating several root development, photosynthesis, and pigmentation-related genes as seen by the impairment of these processes in h2a.x ko plants. H2A.X also suppressed global deposition of H3K9me2 repressive mark by restricting activity of H2A variant H2A.W. In agreement with this, there was a genome-wide re-localization of H2A.W to TEs and a few genes in h2a.x ko plants. H2A.X overexpressing plants exhibited stress phenotypes including increased anthocyanin levels, mimicking the transcriptome of DNA damaged wildtype plants. The transcriptome of kd lines of FACT complex, a known chaperone of H2A.X, was largely similar to that of h2a.x ko, suggesting that the development-associated functions of FACT is at least partially due to H2A.X. These results suggest a key role of H2A.X in regulating competing histone marks and this function might be conserved across plants.', 'pic/ncbi_logo.png', NULL, 'approved'),
(58, 'GSE308770', 'Distinct development-associated roles of rice histone variant H2A.X in suppressing deposition of active H3K4me3 marks and in restricting H2A.W incorporation [ChIP-Seq]', 'Histone variant H2A.X is a well-conserved protein that plays crucial roles in mediating DNA damage response across eukaryotes. Although H2A.X expresses even without any stress, and decorates gene bodies of actively expressed genes, it is not known if H2A.X has functions beyond DNA damage repair. Using genetic, high throughput genomics and molecular approaches, we identified a previously unappreciated role of H2A.X in regulating development-associated genes. H2A.X suppressed the deposition of active H3K4me3 marks over gene bodies and Transposable elements (TE)s, specifically regulating several root development, photosynthesis, and pigmentation-related genes as seen by the impairment of these processes in h2a.x ko plants. H2A.X also suppressed global deposition of H3K9me2 repressive mark by restricting activity of H2A variant H2A.W. In agreement with this, there was a genome-wide re-localization of H2A.W to TEs and a few genes in h2a.x ko plants. H2A.X overexpressing plants exhibited stress phenotypes including increased anthocyanin levels, mimicking the transcriptome of DNA damaged wildtype plants. The transcriptome of kd lines of FACT complex, a known chaperone of H2A.X, was largely similar to that of h2a.x ko, suggesting that the development-associated functions of FACT is at least partially due to H2A.X. These results suggest a key role of H2A.X in regulating competing histone marks and this function might be conserved across plants.', 'pic/ncbi_logo.png', NULL, 'approved'),
(59, 'GSE303460', 'Spatiotemporal single-cell atlas of suture stem cell dynamics in craniosynostosis [scRNA-Seq]', 'Craniosynostosis is a congenital craniofacial disorder marked by premature suture fusion and aberrant skull morphogenesis. Yet the cellular dynamics and regulatory mechanisms of suture mesenchymal stem cells (SuSCs) in this disease remain largely unknown. Here, we present a comprehensive spatiotemporal atlas of SuSCs integrating single-cell and 2 μm-resolution spatial transcriptomics in Fgfr2C342Y/+, a model that recapitulates features of human Crouzon syndrome, alongside wild-type controls across three key developmental stages (E14.5, E18.5, and P3). By integrating morphology-based cell segmentation with machine-learning classification, we achieved single-cell spatial resolution in mapping Visium HD data. Leveraging this resource, we reveal disruptions in SuSC fate, niche composition, and intercellular signaling across developmental stages in craniosynostotic sutures. Downstream analyses identify Foxa3 as a master transcriptional regulator of these fate shifts and implicate specific immune- and suture meningeal fibroblast–derived signals in driving pathological ossification. Together, our work fills a gap in disease-model single-cell spatial-omics, providing a high-resolution roadmap of SuSC dynamics in craniosynostosis and uncovering candidate molecular targets for future therapeutic strategies.', 'pic/ncbi_logo.png', NULL, 'approved'),
(60, 'GSE303446', 'Beyond CD30 Targeting: Brentuximab Vedotin Triggers Immunogenic Cell Death and Antitumor Immunity in Mycosis Fungoides, Overcoming Resistance via BCL2 Inhibition', 'Background: Mycosis fungoides (MF), the most common subtype of cutaneous T cell lymphoma (CTCL), has poor prognosis in advanced stages due to lack of effective therapies. Brentuximab vedotin (BV), an antigen-drug conjugate targeting CD30, is approved for CD30+ MF after prior systemic treatment. However, many patients develop resistance with unclarified mechanisms. Method: We conducted single-cell RNA sequencing on 13 paired tumor samples from 6 CD30+ MF patients treated with BV. Eight post-treatment samples were grouped into responsive (n = 5) and non-responsive (n = 3) lesions based on pathologic response. Combination effects of BV and BCL2 inhibitors were assessed in CD30+ CTCL cell lines. Result: BV induced immunogenic cell death (ICD) in both CD30+ and CD30- malignant T cells, enhancing their MHC-II-mediated antigen presentation in responsive lesions. Besides, BV specifically enhanced the   IFNα/γ responses in CD30- malignant T cells. These coincided with TME reprogramming: diminished immunosuppressive function of Tregs and activated antitumor immunity mediated by dendritic cells, CD8+ T and NK cells. In non-responsive lesions, resistance was driven by distinct mechanisms: CD30+ malignant T cells upregulated the drug efflux transporter ABCB1 and exhibited impaired endosomal processing, while CD30- tumor cells overexpressed the anti-apoptotic protein BCL2 and displayed blunted IFN response. We confirmed potent synergy between BV and BCL2 inhibitors in CTCL cell lines, overcoming resistance. Conclusion: Beyond direct CD30+ targeting, BV transforms the immunosuppressive milieu by inducing ICD in  tumor cells and suppressing Tregs. Resistance involves ABCB1 upregulation in CD30+ cells and BCL2-mediated survival in CD30- cells. Combining BV with BCL2 inhibitors represents a promising strategy to overcome resistance in CD30+ CTCL.', 'pic/ncbi_logo.png', NULL, 'approved'),
(61, 'GSE303344', 'Spatiotemporal single-cell atlas of suture stem cell dynamics in craniosynostosis', 'Craniosynostosis is a congenital craniofacial disorder marked by premature suture fusion and aberrant skull morphogenesis. Yet the cellular dynamics and regulatory mechanisms of suture mesenchymal stem cells (SuSCs) in this disease remain largely unknown. Here, we present a comprehensive spatiotemporal atlas of SuSCs integrating single-cell and 2 μm-resolution spatial transcriptomics in Fgfr2C342Y/+, a model that recapitulates features of human Crouzon syndrome, alongside wild-type controls across three key developmental stages (E14.5, E18.5, and P3). By integrating morphology-based cell segmentation with machine-learning classification, we achieved single-cell spatial resolution in mapping Visium HD data. Leveraging this resource, we reveal disruptions in SuSC fate, niche composition, and intercellular signaling across developmental stages in craniosynostotic sutures. Downstream analyses identify Foxa3 as a master transcriptional regulator of these fate shifts and implicate specific immune- and suture meningeal fibroblast–derived signals in driving pathological ossification. Together, our work fills a gap in disease-model single-cell spatial-omics, providing a high-resolution roadmap of SuSC dynamics in craniosynostosis and uncovering candidate molecular targets for future therapeutic strategies', 'pic/ncbi_logo.png', NULL, 'approved'),
(62, 'GSE299927', 'Molecular evolution of RV dysfunction snRNAseq analysis', 'We evaluated the effects of pulmonary artery banding on the cellular landscape of progressive RV dysfunction using single nucleus RNAseq', 'pic/ncbi_logo.png', NULL, 'approved'),
(63, 'GSE299265', 'Sustained αβ T Cell Effector Activity and Memory Expansion in Children with Congenital Heart Disease', 'Congenital heart disease (CHD) is a major global health problem. Although treatment has improved, children still face comorbidities that may shorten their life. Most studies of the immune system in people with CHD have focused on the quantitative analysis of lymphocyte subpopulations, maturation and T cell receptor repertoires, while knowledge of effector functions is limited. We analysed αβ T cell phenotypes, transcriptomes and functions in children with CHD who underwent cardiac surgery within a year of birth and were followed up five to ten years after thymectomy, in comparison to age-matched healthy controls. We show that children with CHD have immunological alterations, including reduced T cell populations, lower CD4+ or CD8+ T cell proportions, reduced proportions of recent thymic emigrants (RTEs) and naive cells, and an accumulation of memory T cell populations. Single-cell transcriptomics and functional assays revealed high activation states of T cells and higher granzyme and effector cytokine production in children with CHD. Our study provides a foundation for longitudinal studies in children, adults and the elderly to unravel the cause of increased morbidity and mortality in these patients.', 'pic/ncbi_logo.png', NULL, 'approved'),
(64, 'GSE332711', 'CD4/CD8 ratio is associated with structural reorganization of vaccine-induced immune responses in people living with HIV', 'Background: Despite effective antiretroviral therapy and sustained viral suppression, people living with HIV (PLWH) continue to exhibit persistent immune activation and low-grade inflammation. Although the CD4/CD8 ratio is routinely monitored as a marker of immune health, the mechanisms underlying residual immune dysregulation remain incompletely understood. Methods: Peripheral blood mononuclear cells from PLWH and HC were collected before and one month after two doses of mRNA vaccination and analyzed by single-cell RNA sequencing with paired TCR profiling. Differential gene expression (DGE) and protein–protein interaction (PPI) network analyses were performed, and node degree distributions were compared among groups. TCR and bulk BCR repertoires were analyzed, and neutralizing antibody responses were assessed. PLWH were stratified by CD4/CD8 ratio. Results: Stratification by CD4/CD8 ratio revealed distinct immune states in PLWH. Differential genes from the normal CD4/CD8 ratios showed focused transcriptional activation with coordinated chemokine-associated communication, whereas those with low CD4/CD8 ratios exhibited broad transcriptional dysregulation and structural reorganization of gene-expression networks. This network signature was characterized by altered PPI topology and significantly increased monocyte-specific node degree, independent of overall transcriptional complexity. Repertoire analyses demonstrated clonal skewing and reduced clonotype diversity in the low CD4/CD8 ratio group, consistent with impaired immune coordination. Conclusion: Vaccine-induced immune responses in PLWH are shaped by network-level organization associated with CD4/CD8 ratio–defined immune states. Low CD4/CD8 ratio group showed increased monocyte-specific PPI connectivity and clonal imbalance, suggesting altered vaccine-induced response dynamics not captured by conventional clinical markers.', 'pic/ncbi_logo.png', NULL, 'approved'),
(65, 'GSE268368', 'Alterations in Monocyte Reprogramming and Ontogeny Enhance Lipopolysaccharide-Induced Lung Injury in Sepsis Survivor Mice [ATAC-Seq]', 'Sepsis is the leading cause of infection-related hospitalization. Persistent inflammation after sepsis is associated with poor long-term outcomes including rehospitalization for new injurious lung conditions. Prior infection can elicit durable epigenetic changes in immune cells and their progenitors leading to inflammatory reprogramming, but the role of persistent immune programming in mediating complications in sepsis survivors remains unclear. We previously established that survival of murine polymicrobial sepsis is associated with enhanced lung injury responses to lipopolysaccharide. This is associated with enhanced cytokine expression in classical (Ly6Chi) monocytes in the lungs, suggesting a role for monocytes in enhancing lung injury in sepsis survival. We performed monocyte depletion and adoptive transfer in mice three weeks and three months after sepsis. We establish that Ly6Chi monocytes are persistently reprogrammed to enhance lung injury and identify neutrophil degranulation as a potential mechanism. Three weeks after sepsis, murine monocytes show persistently altered transcription and chromatin alterations enriched for TLR4, HIF1α, and JAK-STAT signaling and AP-1 binding consistent with persistent immune reprogramming. As novel Ly6Chi monocyte subsets have been recently identified, but functional relevance remains unknown, we evaluated the presence of monocyte subsets and their association with sepsis and acute lung injury. We show for the first time, to our knowledge, that sepsis provokes an ontogenic shift in monocytes towards a granulocyte-monocyte progenitor-derived neutrophil-like lineage in mice and humans. These data suggest that altered myelopoiesis in sepsis survival may be predictive of poor long-term outcome, to this end we show that monocyte and neutrophil counts are associated with 90-day mortality and are complimentary in predicting outcome. Taken together this work supports a conceptual model whereby prior sepsis elicits durable changes in bone marrow progenitors and a shift in monocyte subsets leading to a predisposition to lung injury. This study highlights gaps in our knowledge relating to the interaction of monocyte subsets and immune reprogramming from prior stimuli in governing the response to organ injury.', 'pic/ncbi_logo.png', NULL, 'approved'),
(66, 'GSE268367', 'Altered Monocyte Inflammatory Program and Ontogeny Mediate Enhanced Lung Injury in Sepsis Survivors [RNA-Seq]', 'Persistent inflammation after sepsis is associated with poor long-term outcomes including rehospitalization for new injurious lung conditions. Prior infection elicits durable reprogramming in myeloid cells and their progenitors in other contexts. We previously established a murine model of sepsis survival induced by cecal ligation and puncture which results in enhanced lung injury responses to lipopolysaccharide. In this model, classical (Ly6Chi) monocytes in the lungs of post-sepsis mice expressed more inflammatory cytokines, suggesting a primed phenotype and direct role in enhancing lung injury. Therefore, we hypothesized that persistent inflammatory reprogramming of monocytes predisposes to lung injury in sepsis survivors. Here, deplete and/or adoptively transfer monocytes three weeks and three months after sepsis in mice. We evaluate transcriptomic and epigenomic pathways associated with monocyte reprogramming and explore the effect of sepsis on novel monocyte subsets in mice and humans. We find that monocytes from sepsis survivor mice mediate enhanced lung injury responses to LPS and promote neutrophil degranulation. Sepsis elicits durable changes monocytes characterized by JAK-STAT signaling and AP-1 binding and shifts in monocytes and progenitors toward the neutrophil-like subset. We confirm a similar monocyte subset shift in humans with acute sepsis and show that monocyte counts are predictive of 90-day mortality in a cohort of adult sepsis patients. We conclude that sepsis induces inflammatory memory affecting bone marrow progenitors and monocyte subsets predisposing to lung injury. This study sheds light on the interaction of monocyte subsets and immune reprogramming from prior stimuli in governing secondary organ injury responses.', 'pic/ncbi_logo.png', NULL, 'approved'),
(67, 'GSE330465', 'Gene expression profiling of neoadjuvant ABFOLFOX treatment in patients with unresectable colorectal cancer with liver metastases', 'To characterize the impact of neoadjuvant ABFOLFOX (Atezolizumab, Bevacizumab, and FOLFOX) therapy on the tumor microenvironment of colorectal liver metastases (CRLM), we performed a comprehensive molecular analysis using bulk RNA-seq. The study comprised two distinct cohorts: a cross-sectional cohort (Cohort A, n=60) and a prospective longitudinal cohort (Cohort B, n=20). Cohort A included patients who underwent hepatic surgery, categorized into three groups (n=20 each): those who underwent upfront surgery (G1 group); those treated with neoadjuvant chemotherapy (NAC; FOLFOX or FOLFIRI) (G2 group); and those treated with NAC plus bevacizumab (G3 group). In Cohort B, CRLM specimens were analyzed at three serial time points: T0 (baseline liver biopsy), T1 (biopsy after atezolizumab monotherapy), and T2 (surgical or biopsied specimen after ABFOLFOX). Our findings suggest a progressive increase in immunogenicity within the CRLM tumor ecosystem following treatment. In particular, the monocyte lineage and SP140 regulon appear to serve as potential mediators of the observed therapeutic benefits. This submission presents the transcriptomic data supporting the interplay between systemic therapy and the immune landscape in CRLM.', 'pic/ncbi_logo.png', NULL, 'approved'),
(68, 'GSE304960', 'Extracellular vesicles derived from Enterococcus faecalis: inflammatory activation does not require internalization', 'Enterococcus faecalis is a common gut commensal Gram-positive bacterium that can act as an opportunistic pathogen and is frequently associated with nosocomial and iatrogenic bloodstream infections, such as bacteremia and endocarditis. Bacteria-derived extracellular vesicles (EVs) emerge as key mediators of host-bacteria communication with immunomodulatory roles and mechanistic participation in pathophysiological processes, such as inflammation and infection. However, the functional impact of E. faecalis-derived EVs (Ef-EVs) on host responses and their potential role in shaping host responses during infection remain unclear. In this work, we investigated the immunomodulatory effects of Ef-EVs in vitro on NF-κB/AP-1 reporter cells, primary human monocyte-derived macrophages (HMDMs), human umbilical vein endothelial cells (HUVECs), and macrophages derived from in vivo Ef-EV-treated zebrafish larvae. We found that Ef-EVs can induce pro-inflammatory responses in host macrophages via Toll-like receptor 2 (TLR2) signaling. Using bottom-up assembled bacterial EVs functionalized with the synthetic bacterial ligands as a minimalistic approach to study mechanisms of EV signaling, we demonstrate that Ef-EVs target the plasma membrane TLR2 to induce inflammation in a process uncoupled from their internalization. Furthermore, we found that Ef-EVs induce metabolic reprogramming towards a pro-inflammatory, glycolytic phenotype. Our findings showcase a previously understudied role of Gram-positive EVs in modulating immune signaling and metabolic pathways, advancing our understanding of host-pathogen communication.', 'pic/ncbi_logo.png', NULL, 'approved'),
(69, 'GSE290317', 'Immune hyperactivity in hemodialysis patients is associated with interferon gamma-induced trained immunity', 'Hemodialysis patients experience persistent inflammation due to increased production of pro-inflammatory monocytes. We hypothesized that the persistent hyper-responsiveness of innate immune cells in these patients is driven by trained immunity, a form of innate immune memory. This observational study aimed to investigate the presence of trained immunity responses in hemodialysis patients and to elucidate the molecular mechanisms underlying it.  We profiled innate immune cell subsets by flow cytometry and cytokine responses of hemodialysis patients and healthy controls following ex vivo stimulation of peripheral blood mononuclear cells with Toll-like receptor (TLR) agonists. Plasma concentrations of inflammatory markers were assessed using the Olink Proximity Extension Assay, while whole-genome RNA sequencing was performed on circulating monocytes to identify genes associated with trained immunity. In vitro assays were conducted to explore the role of interferon gamma (IFN-γ) in mediating trained immunity.  Hemodialysis patients displayed elevated monocyte counts and their cells showed significantly heightened cytokine responses to TLR stimulation, indicative of trained immunity. Importantly, plasma IFN-γ concentrations positively correlated with these cytokine responses. Gene expression analysis revealed enrichment of interferon response pathways, particularly in patients whose monocytes exhibited the most pronounced cytokine production upon restimulation. In vitro experiments confirmed that trained immunity induction depends on IFN-γ, produced by CD4+ T cells.  Our findings demonstrate that hemodialysis patients display a dysregulated immune response characterized by trained immunity and that this might be mediated by IFN-γ. These insights suggest that targeting IFN-γ could be a promising strategy to mitigate damaging immune hyperactivity in dialysis patients.', 'pic/ncbi_logo.png', NULL, 'approved'),
(70, 'GSE333058', 'Mint-ChIP-seq from CD14-positive monocyte (ENCSR465SUK).', 'H3K27me3 Mint-ChIP-seq on human CD14-positive monocyte  For data usage terms and conditions, please refer to http://www.genome.gov/27528022 and http://www.genome.gov/Pages/Research/ENCODE/ENCODE_Data_Use_Policy_for_External_Users_03-07-14.pdf', 'pic/ncbi_logo.png', NULL, 'approved'),
(71, 'GSE333018', 'Mint-ChIP-seq from CD14-positive monocyte (ENCSR167XYG).', 'H3K9me3 Mint-ChIP-seq on human CD14-positive monocyte  For data usage terms and conditions, please refer to http://www.genome.gov/27528022 and http://www.genome.gov/Pages/Research/ENCODE/ENCODE_Data_Use_Policy_for_External_Users_03-07-14.pdf', 'pic/ncbi_logo.png', NULL, 'approved');

-- --------------------------------------------------------

--
-- Table structure for table `upgrade_requests`
--

CREATE TABLE `upgrade_requests` (
  `id` int NOT NULL,
  `user_id` int NOT NULL,
  `request_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `reason` text NOT NULL,
  `status` enum('pending','accepted','rejected') DEFAULT 'pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `username` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `passwor` varchar(255) DEFAULT NULL,
  `role` enum('admin','user') NOT NULL DEFAULT 'user',
  `otp_code` varchar(10) DEFAULT NULL,
  `otp_expire` datetime DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `delete_otp` varchar(6) DEFAULT NULL,
  `delete_expire` datetime DEFAULT NULL,
  `login_attempts` int DEFAULT '0',
  `last_attempt_time` datetime DEFAULT NULL,
  `pending_email` varchar(255) DEFAULT NULL,
  `reset_code` varchar(10) DEFAULT NULL,
  `reset_expire` datetime DEFAULT NULL,
  `pending_phone` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `passwor`, `role`, `otp_code`, `otp_expire`, `email`, `phone`, `delete_otp`, `delete_expire`, `login_attempts`, `last_attempt_time`, `pending_email`, `reset_code`, `reset_expire`, `pending_phone`) VALUES
(46, 'rrr', '$2y$10$0N3uGpaZLBeNR7ESSSubyOHr3aVUR5AYAM3klte.Wdnr/lpGdYpL.', 'admin', '540520', '2026-04-04 06:04:13', 'abdelrhmand256@gmail.com', '+201037284457', '920935', '2026-04-04 06:04:49', 0, '2026-05-20 08:15:37', NULL, NULL, '2026-05-28 14:22:03', '+201037284457'),
(47, 'aaa', '$2y$10$.Zlhvwy0pd3dB7v8v48S0ue4rxTPU/d8Ar3VnSBeeseZNFvrTt7Me', 'admin', NULL, NULL, '29211260100998@cis.asu.edu.eg', '+201037284457', NULL, NULL, 0, NULL, NULL, NULL, NULL, '+201037284457'),
(48, 'sss', '$2y$10$1qea4pl0huBHYOtf6tNLDeu138Mo82admZC62Dv87rxu9qi91FwtC', 'user', NULL, NULL, 'dergo2@outlook.com', '+201122663933', NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `failed_attempts`
--
ALTER TABLE `failed_attempts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `sections`
--
ALTER TABLE `sections`
  ADD PRIMARY KEY (`s_id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `terms`
--
ALTER TABLE `terms`
  ADD PRIMARY KEY (`id`),
  ADD KEY `terms_ibfk_1` (`user_id`);

--
-- Indexes for table `upgrade_requests`
--
ALTER TABLE `upgrade_requests`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `failed_attempts`
--
ALTER TABLE `failed_attempts`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `sections`
--
ALTER TABLE `sections`
  MODIFY `s_id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT for table `terms`
--
ALTER TABLE `terms`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=72;

--
-- AUTO_INCREMENT for table `upgrade_requests`
--
ALTER TABLE `upgrade_requests`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `sections`
--
ALTER TABLE `sections`
  ADD CONSTRAINT `sections_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `terms`
--
ALTER TABLE `terms`
  ADD CONSTRAINT `terms_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `upgrade_requests`
--
ALTER TABLE `upgrade_requests`
  ADD CONSTRAINT `upgrade_requests_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
